### ISSUE TITLE
In app modal "comment" button didn't work

### ISSUE THREAD

**Issue by tazard** [Perth-Artifactory/taiga_sync#96]
The "comment" button on taiga issue 81 didn't work. I opened the issue from a slack notification about new issue/comment. Then messages and opened the watched issue. Next wrote a comment and hit "comment" button. It spins and stops but nothing happens. Checking web app confirms it did not post. Copies text into web app and posted comment fine. Returned to slack taiga app but still won't post comment as in screenshot below.

![Image](https://github.com/user-attachments/assets/f8e73582-ad46-4b86-88a8-992649006629)

**Comment by FletcherAU** [comment]
Ty for the report, reproducible on my end :)
